### ISSUE TITLE
📧 Build J-Mail - Version 3

### ISSUE THREAD

**Issue by robin-macpherson** [Journaly/journaly#763]
#### Description

There's a series of nice improvements that could be made to J-Mail that I do think are really important and, to be honest, I think would bring that particular feature to completion.

#### Tasks
- [ ] Improve the scale at which the system can operate at in terms of volume of notifications/content in an email
- [ ] Handle the issue where people like Linda seem to somewhat frequently receive two emails, the latter often being empty and only containing thanks info
- [ ] Improve styling so that notifications for a single post get bundled together more nicely - the title and image only need to be displayed once and then we can summarize the notifications underneath
- [ ] Set up C.I. for J-Mail with #562 
- [ ] Handle visual bug on Outlook with #698 
- [ ] Update Serverless verions and handle deprecation warnings with #589
